/**
 * SERVER-ONLY: the Kysely client over Cloudflare D1. The main `db` is the raw
 * Kysely instance; rpc-server.ts wraps every query per-call with db-result's
 * `tryDb` (thunk form). Decode functions map the raw snake_case rows
 * (millisecond timestamps, JSON-text list columns, 0/1 booleans) onto the
 * camelCase `Stored*` shapes the models declare. `authRawDb` is a separate
 * instance for better-auth: camelCase type keys mapped to the snake_case D1
 * columns via CamelCasePlugin.
 *
 * `env` comes from the workerd runtime (`cloudflare:workers`); its shape is
 * generated by `wrangler types` into worker-configuration.d.ts. This module
 * must never be imported from client code — the only importers are the RPC
 * server (src/rpc-server.ts) and the server functions in src/ssr.ts.
 */
import { env } from 'cloudflare:workers'
import { CamelCasePlugin, Kysely } from 'kysely'
import { D1Dialect } from 'kysely-d1'
import type {
  AuditLogTable,
  AuthDB,
  BusinessTable,
  ContactTable,
  DB,
  DealTable,
  GuideTable,
  GuideVenueTable,
  HotelTable,
  StoredAuditEntry,
  StoredBusiness,
  StoredContact,
  StoredDeal,
  StoredGuide,
  StoredGuideVenue,
  StoredHotel,
  StoredLifecycleEvent,
  StoredVenue,
  StoredVenueAward,
  VenueAwardTable,
  VenueLifecycleEventTable,
  VenueTable,
} from './schema.js'

const rawDb = new Kysely<DB>({ dialect: new D1Dialect({ database: env.DB }) })

/** The Kysely db (unwrapped) — rpc-server wraps queries with tryDb per call. */
export { rawDb }

/** Auth-facing Kysely instance: camelCase type keys, CamelCasePlugin maps them
 * to the snake_case D1 columns. better-auth's kysely adapter queries by type
 * key, so it must see this shape — not the raw snake_case `DB`. */
export const authRawDb = new Kysely<AuthDB>({
  dialect: new D1Dialect({ database: env.DB }),
  plugins: [new CamelCasePlugin()],
})

/** The Kysely db (unwrapped). Every query is wrapped per-call with db-result's
 * `tryDb` (thunk form) in rpc-server.ts — the kyselyTryDb whole-db wrapper's
 * mapped type exhausts tsc's heap on a 17-table `DB` interface. */
export const db = rawDb
export type Db = typeof db

/** Milliseconds-since-epoch — the storage unit of every timestamp column. */
export const epochMs = (date: Date): number => date.getTime()

const parseJson = <T>(text: string): T => JSON.parse(text) as T
const fromMs = (ms: number | null): Date | null => (ms === null ? null : new Date(ms))
const toBool = (v: 0 | 1): boolean => v === 1

// ═══════════════════════════════════════════════════════════════════════════
// Decode — raw row → Stored shape. Written field-by-field (never spread) so a
// new column in schema.ts is a deliberate decision here, not an accident on
// the wire.
// ═══════════════════════════════════════════════════════════════════════════

export const decodeVenue = (row: VenueTable): StoredVenue => ({
  id: row.id,
  name: row.name,
  category: row.category,
  categorySecondary: row.category_secondary,
  status: row.status,
  orderKey: row.order_key,
  cuisine: row.cuisine,
  priceLevel: row.price_level,
  tags: parseJson<string[]>(row.tags),
  note: row.note,
  recommendedDishes: parseJson<string[]>(row.recommended_dishes),
  lastVerifiedAt: fromMs(row.last_verified_at),
  confidence: row.confidence,
  source: row.source,
  address: row.address,
  lat: row.lat,
  lon: row.lon,
  googlePlacesId: row.google_places_id,
  dineoutId: row.dineout_id,
  website: row.website,
  phone: row.phone,
  openingHours: row.opening_hours,
  photos: parseJson<string[]>(row.photos),
  createdAt: new Date(row.created_at),
})

export const decodeVenueAward = (row: VenueAwardTable): StoredVenueAward => ({
  id: row.id,
  venueId: row.venue_id,
  awardType: row.award_type,
  title: row.title,
  url: row.url,
  createdAt: new Date(row.created_at),
})

export const decodeLifecycleEvent = (row: VenueLifecycleEventTable): StoredLifecycleEvent => ({
  id: row.id,
  venueId: row.venue_id,
  type: row.type,
  startedAt: new Date(row.started_at),
  endedAt: fromMs(row.ended_at),
  note: row.note,
})

export const decodeAuditEntry = (row: AuditLogTable): StoredAuditEntry => ({
  id: row.id,
  actor: row.actor,
  action: row.action,
  entityType: row.entity_type,
  entityId: row.entity_id,
  before: row.before,
  after: row.after,
  at: new Date(row.at),
})

export const decodeBusiness = (row: BusinessTable): StoredBusiness => ({
  id: row.id,
  name: row.name,
  website: row.website,
  industry: row.industry,
  notes: row.notes,
})

export const decodeHotel = (row: HotelTable): StoredHotel => ({
  id: row.id,
  businessId: row.business_id,
  name: row.name,
  address: row.address,
  lat: row.lat,
  lon: row.lon,
  roomCount: row.room_count,
  website: row.website,
})

export const decodeContact = (row: ContactTable): StoredContact => ({
  id: row.id,
  businessId: row.business_id,
  hotelId: row.hotel_id,
  firstName: row.first_name,
  lastName: row.last_name,
  email: row.email,
  phone: row.phone,
  title: row.title,
  isDecisionMaker: toBool(row.is_decision_maker),
})

export const decodeDeal = (row: DealTable): StoredDeal => ({
  id: row.id,
  businessId: row.business_id,
  name: row.name,
  stage: row.stage,
  pricePerRoom: row.price_per_room,
  annualValue: row.annual_value,
  startDate: fromMs(row.start_date),
  renewalDate: fromMs(row.renewal_date),
  notes: row.notes,
})

export const decodeGuide = (row: GuideTable): StoredGuide => ({
  id: row.id,
  hotelId: row.hotel_id,
  slug: row.slug,
  status: row.status,
  radiusMin: row.radius_min,
  targetCount: row.target_count,
  generatedAt: fromMs(row.generated_at),
})

export const decodeGuideVenue = (row: GuideVenueTable): StoredGuideVenue => ({
  id: row.id,
  guideId: row.guide_id,
  venueId: row.venue_id,
  status: row.status,
  orderKey: row.order_key,
  overrideText: row.override_text,
  pinned: toBool(row.pinned),
})
