/**
 * SERVER-ONLY: the Drizzle client over Cloudflare D1.
 *
 * `env` comes from the workerd runtime (`cloudflare:workers`); its shape is
 * generated by `wrangler types` into worker-configuration.d.ts. This module
 * must never be imported from client code — the only importers are the RPC
 * server (src/rpc-server.ts) and the server functions in src/ssr.ts.
 */
import { env } from 'cloudflare:workers'
import { drizzle } from 'drizzle-orm/d1'

export const db = drizzle(env.DB)
export type Db = typeof db

export { auditLog, businesses, contacts, deals, guideExcludes, guideVenues, guides, hotels, venueLifecycleEvents, venues } from './schema.js'
