/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiQrRouteImport } from './routes/api.qr'
import { Route as ApiRpcRouteImport } from './routes/api.rpc'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVenuesRouteImport } from './routes/app.venues'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppVenuesVenueIdRouteImport } from './routes/app.venues_.$venueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrRoute = ApiQrRouteImport.update({
  id: '/api/qr',
  path: '/api/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVenuesRoute = AppVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AppRoute,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVenuesVenueIdRoute = AppVenuesVenueIdRouteImport.update({
  id: '/venues_/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/qr': typeof ApiQrRoute
  '/api/rpc': typeof ApiRpcRoute
  '/app/venues': typeof AppVenuesRoute
  '/g/$slug': typeof GSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/qr': typeof ApiQrRoute
  '/api/rpc': typeof ApiRpcRoute
  '/app/venues': typeof AppVenuesRoute
  '/g/$slug': typeof GSlugRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/qr': typeof ApiQrRoute
  '/api/rpc': typeof ApiRpcRoute
  '/app/venues': typeof AppVenuesRoute
  '/g/$slug': typeof GSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/venues_/$venueId': typeof AppVenuesVenueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/qr'
    | '/api/rpc'
    | '/app/venues'
    | '/g/$slug'
    | '/app/'
    | '/api/auth/$'
    | '/app/venues/$venueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/qr'
    | '/api/rpc'
    | '/app/venues'
    | '/g/$slug'
    | '/app'
    | '/api/auth/$'
    | '/app/venues/$venueId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/qr'
    | '/api/rpc'
    | '/app/venues'
    | '/g/$slug'
    | '/app/'
    | '/api/auth/$'
    | '/app/venues_/$venueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiQrRoute: typeof ApiQrRoute
  ApiRpcRoute: typeof ApiRpcRoute
  GSlugRoute: typeof GSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr': {
      id: '/api/qr'
      path: '/api/qr'
      fullPath: '/api/qr'
      preLoaderRoute: typeof ApiQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/venues': {
      id: '/app/venues'
      path: '/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppVenuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/venues_/$venueId': {
      id: '/app/venues_/$venueId'
      path: '/venues/$venueId'
      fullPath: '/app/venues/$venueId'
      preLoaderRoute: typeof AppVenuesVenueIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppVenuesRoute: typeof AppVenuesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVenuesVenueIdRoute: typeof AppVenuesVenueIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppVenuesRoute: AppVenuesRoute,
  AppIndexRoute: AppIndexRoute,
  AppVenuesVenueIdRoute: AppVenuesVenueIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiQrRoute: ApiQrRoute,
  ApiRpcRoute: ApiRpcRoute,
  GSlugRoute: GSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
